"""initial unified wms schema

Revision ID: 9f4581f6e261
Revises:
Create Date: 2026-07-28 15:19:27.079270

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f4581f6e261'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.String(length=500), server_default='', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('status', sa.String(length=16), server_default='active', nullable=False),
    sa.CheckConstraint("status IN ('active','inactive')", name=op.f('ck_categories_valid_status')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_categories')),
    sa.UniqueConstraint('code', name=op.f('uq_categories_code')),
    sa.UniqueConstraint('name', name=op.f('uq_categories_name'))
    )
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_categories_status'), ['status'], unique=False)

    op.create_table('customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=255), server_default='', nullable=False),
    sa.Column('phone', sa.String(length=30), server_default='', nullable=False),
    sa.Column('contract_emails', sa.Text(), server_default='', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('status', sa.String(length=16), server_default='active', nullable=False),
    sa.CheckConstraint("status IN ('active','inactive')", name=op.f('ck_customers_valid_status')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_customers')),
    sa.UniqueConstraint('code', name=op.f('uq_customers_code'))
    )
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_customers_status'), ['status'], unique=False)

    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_roles')),
    sa.UniqueConstraint('code', name=op.f('uq_roles_code'))
    )
    op.create_table('suppliers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=255), server_default='', nullable=False),
    sa.Column('phone', sa.String(length=30), server_default='', nullable=False),
    sa.Column('address', sa.String(length=500), server_default='', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('status', sa.String(length=16), server_default='active', nullable=False),
    sa.CheckConstraint("status IN ('active','inactive')", name=op.f('ck_suppliers_valid_status')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_suppliers')),
    sa.UniqueConstraint('code', name=op.f('uq_suppliers_code'))
    )
    with op.batch_alter_table('suppliers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_suppliers_status'), ['status'], unique=False)

    op.create_table('units',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('allow_break_pack', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=16), server_default='active', nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_units')),
    sa.UniqueConstraint('code', name=op.f('uq_units_code'))
    )
    with op.batch_alter_table('units', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_units_status'), ['status'], unique=False)

    op.create_table('warehouses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('address', sa.String(length=500), server_default='', nullable=False),
    sa.Column('status', sa.String(length=16), server_default='active', nullable=False),
    sa.CheckConstraint("status IN ('active','inactive')", name=op.f('ck_warehouses_valid_status')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_warehouses')),
    sa.UniqueConstraint('code', name=op.f('uq_warehouses_code'))
    )
    with op.batch_alter_table('warehouses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_warehouses_status'), ['status'], unique=False)

    op.create_table('customer_contract_emails',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('normalized_email', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('status', sa.String(length=16), server_default='active', nullable=False),
    sa.CheckConstraint("status IN ('active','inactive')", name=op.f('ck_customer_contract_emails_valid_status')),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name=op.f('fk_customer_contract_emails_customer_id_customers'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_customer_contract_emails')),
    sa.UniqueConstraint('customer_id', 'normalized_email', name='uq_customer_contract_emails_customer_email')
    )
    with op.batch_alter_table('customer_contract_emails', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_customer_contract_emails_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_customer_contract_emails_normalized_email'), ['normalized_email'], unique=False)
        batch_op.create_index(batch_op.f('ix_customer_contract_emails_status'), ['status'], unique=False)

    op.create_table('inventory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sku', sa.String(length=40), nullable=False),
    sa.Column('barcode', sa.String(length=100), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('warehouse_id', sa.Integer(), nullable=False),
    sa.Column('unit', sa.String(length=40), nullable=False),
    sa.Column('unit_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=18, scale=3), server_default='0', nullable=False),
    sa.Column('min_quantity', sa.Numeric(precision=18, scale=3), server_default='0', nullable=False),
    sa.Column('location', sa.String(length=100), server_default='', nullable=False),
    sa.Column('description', sa.String(length=1000), server_default='', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('status', sa.String(length=16), server_default='active', nullable=False),
    sa.CheckConstraint("status IN ('active','inactive')", name=op.f('ck_inventory_valid_status')),
    sa.CheckConstraint('min_quantity >= 0', name=op.f('ck_inventory_minimum_nonnegative')),
    sa.CheckConstraint('quantity >= 0', name=op.f('ck_inventory_quantity_nonnegative')),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name=op.f('fk_inventory_category_id_categories'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], name=op.f('fk_inventory_unit_id_units')),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], name=op.f('fk_inventory_warehouse_id_warehouses'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_inventory')),
    sa.UniqueConstraint('sku', name=op.f('uq_inventory_sku'))
    )
    with op.batch_alter_table('inventory', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inventory_category_id'), ['category_id'], unique=False)
        batch_op.create_index('ix_inventory_name', ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_unit_id'), ['unit_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_warehouse_id'), ['warehouse_id'], unique=False)
        batch_op.create_index('uq_inventory_barcode_not_null', ['barcode'], unique=True, sqlite_where=sa.text('barcode IS NOT NULL'), mssql_where=sa.text('barcode IS NOT NULL'))

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=30), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=30), server_default='', nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('avatar_initials', sa.String(length=8), server_default='', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("role IN ('admin','cs','warehouse','manager','staff')", name=op.f('ck_users_valid_role')),
    sa.CheckConstraint("status IN ('active','locked')", name=op.f('ck_users_valid_status')),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_users_role_id_roles')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email')),
    sa.UniqueConstraint('username', name=op.f('uq_users_username'))
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_role_id'), ['role_id'], unique=False)

    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('entity_type', sa.String(length=80), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('details', sa.Text(), server_default='{}', nullable=False),
    sa.Column('ip_address', sa.String(length=64), server_default='', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_audit_logs_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_user_id'), ['user_id'], unique=False)

    op.create_table('inventory_adjustments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inventory_id', sa.Integer(), nullable=False),
    sa.Column('old_quantity', sa.Numeric(precision=18, scale=3), nullable=False),
    sa.Column('new_quantity', sa.Numeric(precision=18, scale=3), nullable=False),
    sa.Column('difference', sa.Numeric(precision=18, scale=3), nullable=False),
    sa.Column('reason', sa.String(length=200), nullable=False),
    sa.Column('note', sa.String(length=500), server_default='', nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('new_quantity >= 0', name=op.f('ck_inventory_adjustments_new_nonnegative')),
    sa.CheckConstraint('old_quantity >= 0', name=op.f('ck_inventory_adjustments_old_nonnegative')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_inventory_adjustments_created_by_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['inventory_id'], ['inventory.id'], name=op.f('fk_inventory_adjustments_inventory_id_inventory'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_inventory_adjustments'))
    )
    with op.batch_alter_table('inventory_adjustments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inventory_adjustments_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_adjustments_inventory_id'), ['inventory_id'], unique=False)

    op.create_table('inventory_lots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('warehouse_id', sa.Integer(), nullable=False),
    sa.Column('unit', sa.String(length=40), nullable=False),
    sa.Column('pallet_id', sa.String(length=100), nullable=False),
    sa.Column('barcode', sa.String(length=100), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=18, scale=3), nullable=False),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('received_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('status', sa.String(length=16), server_default='active', nullable=False),
    sa.CheckConstraint("status IN ('active','depleted','quarantined')", name=op.f('ck_inventory_lots_valid_status')),
    sa.CheckConstraint('quantity >= 0', name=op.f('ck_inventory_lots_quantity_nonnegative')),
    sa.ForeignKeyConstraint(['product_id'], ['inventory.id'], name=op.f('fk_inventory_lots_product_id_inventory'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], name=op.f('fk_inventory_lots_warehouse_id_warehouses'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_inventory_lots')),
    sa.UniqueConstraint('pallet_id', name='uq_inventory_lots_pallet_id')
    )
    with op.batch_alter_table('inventory_lots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inventory_lots_status'), ['status'], unique=False)
        batch_op.create_index('ix_lot_allocation', ['product_id', 'warehouse_id', 'expiry_date', 'received_at'], unique=False)
        batch_op.create_index('uq_inventory_lots_barcode_not_null', ['barcode'], unique=True, sqlite_where=sa.text('barcode IS NOT NULL'), mssql_where=sa.text('barcode IS NOT NULL'))

    op.create_table('receipts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('receipt_type', sa.String(length=16), nullable=False),
    sa.Column('partner_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('supplier_id', sa.Integer(), nullable=True),
    sa.Column('partner_name', sa.String(length=200), nullable=False),
    sa.Column('warehouse_id', sa.Integer(), nullable=False),
    sa.Column('request_email', sa.String(length=255), server_default='', nullable=False),
    sa.Column('container_no', sa.String(length=100), server_default='', nullable=False),
    sa.Column('seal_no', sa.String(length=100), server_default='', nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('note', sa.String(length=1000), server_default='', nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('confirmed_by', sa.Integer(), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("(receipt_type='inbound' AND supplier_id IS NOT NULL AND customer_id IS NULL) OR (receipt_type='outbound' AND customer_id IS NOT NULL AND supplier_id IS NULL)", name=op.f('ck_receipts_partner_matches_type')),
    sa.CheckConstraint("receipt_type IN ('inbound','outbound')", name=op.f('ck_receipts_valid_type')),
    sa.CheckConstraint("status IN ('draft','pending','picking','completed','rejected','cancelled')", name=op.f('ck_receipts_valid_status')),
    sa.ForeignKeyConstraint(['confirmed_by'], ['users.id'], name=op.f('fk_receipts_confirmed_by_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_receipts_created_by_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name=op.f('fk_receipts_customer_id_customers'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], name=op.f('fk_receipts_supplier_id_suppliers'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], name=op.f('fk_receipts_warehouse_id_warehouses'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_receipts')),
    sa.UniqueConstraint('code', name=op.f('uq_receipts_code'))
    )
    with op.batch_alter_table('receipts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_receipts_partner_id'), ['partner_id'], unique=False)
        batch_op.create_index('ix_receipts_type_status', ['receipt_type', 'status'], unique=False)

    op.create_table('stocktakes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('warehouse_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), server_default='draft', nullable=False),
    sa.Column('note', sa.String(length=1000), server_default='', nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('confirmed_by', sa.Integer(), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("status IN ('draft','completed','cancelled')", name=op.f('ck_stocktakes_valid_status')),
    sa.ForeignKeyConstraint(['confirmed_by'], ['users.id'], name=op.f('fk_stocktakes_confirmed_by_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_stocktakes_created_by_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], name=op.f('fk_stocktakes_warehouse_id_warehouses'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stocktakes')),
    sa.UniqueConstraint('code', name=op.f('uq_stocktakes_code'))
    )
    op.create_table('receipt_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('receipt_id', sa.Integer(), nullable=False),
    sa.Column('inventory_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=3), nullable=False),
    sa.Column('accepted_quantity', sa.Numeric(precision=18, scale=3), server_default='0', nullable=False),
    sa.Column('rejected_quantity', sa.Numeric(precision=18, scale=3), server_default='0', nullable=False),
    sa.Column('pallet_id', sa.String(length=100), server_default='', nullable=False),
    sa.Column('barcode', sa.String(length=100), server_default='', nullable=False),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('issue_note', sa.String(length=500), server_default='', nullable=False),
    sa.CheckConstraint('accepted_quantity >= 0', name=op.f('ck_receipt_items_accepted_nonnegative')),
    sa.CheckConstraint('quantity > 0', name=op.f('ck_receipt_items_quantity_positive')),
    sa.ForeignKeyConstraint(['inventory_id'], ['inventory.id'], name=op.f('fk_receipt_items_inventory_id_inventory'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['receipt_id'], ['receipts.id'], name=op.f('fk_receipt_items_receipt_id_receipts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_receipt_items')),
    sa.UniqueConstraint('receipt_id', 'inventory_id', 'pallet_id', name='uq_receipt_items_receipt_product_pallet')
    )
    with op.batch_alter_table('receipt_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_receipt_items_receipt_id'), ['receipt_id'], unique=False)

    op.create_table('stock_movements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inventory_id', sa.Integer(), nullable=False),
    sa.Column('lot_id', sa.Integer(), nullable=True),
    sa.Column('movement_type', sa.String(length=20), nullable=False),
    sa.Column('reference_code', sa.String(length=40), nullable=False),
    sa.Column('quantity_change', sa.Numeric(precision=18, scale=3), nullable=False),
    sa.Column('balance_after', sa.Numeric(precision=18, scale=3), nullable=False),
    sa.Column('pallet_id', sa.String(length=100), server_default='', nullable=False),
    sa.Column('reason', sa.String(length=500), server_default='', nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("movement_type IN ('inbound','outbound','stocktake','adjustment')", name=op.f('ck_stock_movements_valid_type')),
    sa.CheckConstraint('balance_after >= 0', name=op.f('ck_stock_movements_balance_nonnegative')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_stock_movements_created_by_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['inventory_id'], ['inventory.id'], name=op.f('fk_stock_movements_inventory_id_inventory'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['lot_id'], ['inventory_lots.id'], name=op.f('fk_stock_movements_lot_id_inventory_lots')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stock_movements')),
    sa.UniqueConstraint('movement_type', 'reference_code', 'inventory_id', 'pallet_id', name='uq_stock_movements_idempotency')
    )
    with op.batch_alter_table('stock_movements', schema=None) as batch_op:
        batch_op.create_index('ix_movement_created', ['created_at'], unique=False)

    op.create_table('stocktake_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stocktake_id', sa.Integer(), nullable=False),
    sa.Column('inventory_id', sa.Integer(), nullable=False),
    sa.Column('system_quantity', sa.Numeric(precision=18, scale=3), nullable=False),
    sa.Column('counted_quantity', sa.Numeric(precision=18, scale=3), nullable=False),
    sa.Column('reason', sa.String(length=500), server_default='', nullable=False),
    sa.CheckConstraint('counted_quantity >= 0', name=op.f('ck_stocktake_items_counted_nonnegative')),
    sa.CheckConstraint('system_quantity >= 0', name=op.f('ck_stocktake_items_system_nonnegative')),
    sa.ForeignKeyConstraint(['inventory_id'], ['inventory.id'], name=op.f('fk_stocktake_items_inventory_id_inventory'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['stocktake_id'], ['stocktakes.id'], name=op.f('fk_stocktake_items_stocktake_id_stocktakes'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stocktake_items')),
    sa.UniqueConstraint('stocktake_id', 'inventory_id', name='uq_stocktake_items_stocktake_product')
    )
    op.create_table('inbound_inspections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('receipt_item_id', sa.Integer(), nullable=False),
    sa.Column('accepted_quantity', sa.Numeric(precision=18, scale=3), nullable=False),
    sa.Column('rejected_quantity', sa.Numeric(precision=18, scale=3), nullable=False),
    sa.Column('issue_note', sa.String(length=500), nullable=False),
    sa.Column('inspected_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('accepted_quantity >= 0', name=op.f('ck_inbound_inspections_accepted_nonnegative')),
    sa.CheckConstraint('rejected_quantity >= 0', name=op.f('ck_inbound_inspections_rejected_nonnegative')),
    sa.ForeignKeyConstraint(['inspected_by'], ['users.id'], name=op.f('fk_inbound_inspections_inspected_by_users')),
    sa.ForeignKeyConstraint(['receipt_item_id'], ['receipt_items.id'], name=op.f('fk_inbound_inspections_receipt_item_id_receipt_items'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_inbound_inspections')),
    sa.UniqueConstraint('receipt_item_id', name='uq_inbound_inspections_receipt_item')
    )
    op.create_table('outbound_allocations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('receipt_item_id', sa.Integer(), nullable=False),
    sa.Column('lot_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=3), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('quantity > 0', name=op.f('ck_outbound_allocations_quantity_positive')),
    sa.ForeignKeyConstraint(['lot_id'], ['inventory_lots.id'], name=op.f('fk_outbound_allocations_lot_id_inventory_lots'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['receipt_item_id'], ['receipt_items.id'], name=op.f('fk_outbound_allocations_receipt_item_id_receipt_items'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_outbound_allocations')),
    sa.UniqueConstraint('receipt_item_id', 'lot_id', name='uq_outbound_allocations_line_lot')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('outbound_allocations')
    op.drop_table('inbound_inspections')
    op.drop_table('stocktake_items')
    with op.batch_alter_table('stock_movements', schema=None) as batch_op:
        batch_op.drop_index('ix_movement_created')

    op.drop_table('stock_movements')
    with op.batch_alter_table('receipt_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_receipt_items_receipt_id'))

    op.drop_table('receipt_items')
    op.drop_table('stocktakes')
    with op.batch_alter_table('receipts', schema=None) as batch_op:
        batch_op.drop_index('ix_receipts_type_status')
        batch_op.drop_index(batch_op.f('ix_receipts_partner_id'))

    op.drop_table('receipts')
    with op.batch_alter_table('inventory_lots', schema=None) as batch_op:
        batch_op.drop_index('uq_inventory_lots_barcode_not_null', sqlite_where=sa.text('barcode IS NOT NULL'), mssql_where=sa.text('barcode IS NOT NULL'))
        batch_op.drop_index('ix_lot_allocation')
        batch_op.drop_index(batch_op.f('ix_inventory_lots_status'))

    op.drop_table('inventory_lots')
    with op.batch_alter_table('inventory_adjustments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inventory_adjustments_inventory_id'))
        batch_op.drop_index(batch_op.f('ix_inventory_adjustments_created_at'))

    op.drop_table('inventory_adjustments')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_user_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_created_at'))

    op.drop_table('audit_logs')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_role_id'))

    op.drop_table('users')
    with op.batch_alter_table('inventory', schema=None) as batch_op:
        batch_op.drop_index('uq_inventory_barcode_not_null', sqlite_where=sa.text('barcode IS NOT NULL'), mssql_where=sa.text('barcode IS NOT NULL'))
        batch_op.drop_index(batch_op.f('ix_inventory_warehouse_id'))
        batch_op.drop_index(batch_op.f('ix_inventory_unit_id'))
        batch_op.drop_index(batch_op.f('ix_inventory_status'))
        batch_op.drop_index('ix_inventory_name')
        batch_op.drop_index(batch_op.f('ix_inventory_category_id'))

    op.drop_table('inventory')
    with op.batch_alter_table('customer_contract_emails', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_customer_contract_emails_status'))
        batch_op.drop_index(batch_op.f('ix_customer_contract_emails_normalized_email'))
        batch_op.drop_index(batch_op.f('ix_customer_contract_emails_customer_id'))

    op.drop_table('customer_contract_emails')
    with op.batch_alter_table('warehouses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_warehouses_status'))

    op.drop_table('warehouses')
    with op.batch_alter_table('units', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_units_status'))

    op.drop_table('units')
    with op.batch_alter_table('suppliers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_suppliers_status'))

    op.drop_table('suppliers')
    op.drop_table('roles')
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_customers_status'))

    op.drop_table('customers')
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_categories_status'))

    op.drop_table('categories')
    # ### end Alembic commands ###
